version: '2'
services:
  fast-data-dev:
    build:
      context: .
      dockerfile: Dockerfile-fast-data-dev
    image: landoop-tutorial/fast-data-dev
    depends_on:
      - activemq
    volumes:
      - ./classAPositionReportSchema.json:/classAPositionReportSchema.json
    environment:
      - ADV_HOST=fast-data-dev
      - FORWARDLOGS=0
      - RUNTESTS=0
    ports:
      - 3030:3030
  activemq:
    build:
      context: .
      dockerfile: Dockerfile-activemq
      args:
        ACTIVEMQ_VERSION: 5.14.2
        ACTIVEMQ_ADMIN: "landoop: landoop, admin"
        ACTIVEMQ_USER: "test: test, user"
    image: landoop-tutorial/activemq
